services:
  archlinux-tw:
    image: bwaycer/archlinux-tw:${BuildTag:-latest}
    build:
      context: ./noTag
      dockerfile: Dockerfile
      args:
        version: latest
        mirrorSite: TW
        timezone: Asia/Taipei
